const STEP_SIMULATION = 'STEP_GRID'
const START_SIMULATION = 'START_SIMULATION'
const STOP_SIMULATION = 'STOP_SIMULATION'
const SET_STEPS_PER_SECOND = 'SET_STEPS_PER_SECOND'

export { STEP_SIMULATION, START_SIMULATION, STOP_SIMULATION, SET_STEPS_PER_SECOND }